# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dca61e73eeaa2625b8da0980cf2720aa32cc7ff0a625581be0d206c42cf836de117249ed57568d32de080bd5ca42a5d61c4b3be92b79a743ae86094411aa5e7a

test:
  secret_key_base: fc749e926208450d893dc898453cfeefd2dc00e03f8a69e6e2be66137ca583537a2ab562ecd8a8fbeb3efa10f91a69bec66b7a0b403387e8157a466b4ba83957

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
